import type {
  ChatMessage,
  Conversation,
  CreditTransaction,
  KnowledgeDoc,
  ModelConfig,
  SkillItem,
  Teacher,
} from "./types";

export const SCHOOL_NAME = "西南大学附属中学两江中学";
export const SCHOOL_SHORT_NAME = "西附两江";
export const PLATFORM_NAME = "智能教育助手";

export const DEMO_PASSWORD = "123456";

export const teachers: Teacher[] = [
  {
    id: "t-001",
    name: "张明",
    employeeNo: "XF2018042",
    subject: "数学",
    department: "高二年级组",
    role: "teacher",
    status: "active",
    password: DEMO_PASSWORD,
    creditBalance: 1280,
    creditMonthlyQuota: 2000,
    lastLoginAt: "2026-09-15 08:12",
    avatarColor: "bg-brand-600",
  },
  {
    id: "t-002",
    name: "李芳",
    employeeNo: "XF2015017",
    subject: "语文",
    department: "高三年级组 · 语文学科组长",
    role: "lead",
    status: "active",
    password: DEMO_PASSWORD,
    creditBalance: 640,
    creditMonthlyQuota: 2000,
    lastLoginAt: "2026-09-14 19:40",
    avatarColor: "bg-gold-500",
  },
  {
    id: "t-003",
    name: "王强",
    employeeNo: "XF2011003",
    subject: "信息技术 · 教务处",
    department: "教务处 / 信息中心",
    role: "admin",
    status: "active",
    password: DEMO_PASSWORD,
    creditBalance: 82000,
    creditMonthlyQuota: 99999,
    lastLoginAt: "2026-09-15 07:55",
    avatarColor: "bg-emerald-600",
  },
  {
    id: "t-004",
    name: "陈静",
    employeeNo: "XF2020091",
    subject: "英语",
    department: "高一年级组",
    role: "teacher",
    status: "active",
    password: DEMO_PASSWORD,
    creditBalance: 95,
    creditMonthlyQuota: 1500,
    lastLoginAt: "2026-09-10 16:02",
    avatarColor: "bg-rose-500",
  },
  {
    id: "t-005",
    name: "刘洋",
    employeeNo: "XF2019056",
    subject: "物理",
    department: "高二年级组",
    role: "teacher",
    status: "disabled",
    password: DEMO_PASSWORD,
    creditBalance: 0,
    creditMonthlyQuota: 1500,
    lastLoginAt: "2026-08-02 09:11",
    avatarColor: "bg-slate-500",
  },
];

export const skills: SkillItem[] = [
  {
    id: "sk-001",
    name: "高考数学命题助手",
    description: "依据最新考纲与历年真题分布，智能生成高三数学单元/模拟卷，自动配参考答案与难度标签。",
    icon: "🧮",
    subject: "数学",
    type: "命题",
    scope: "public",
    status: "published",
    ownerName: "学校教务处",
    usageCount: 1243,
    rating: 4.8,
    official: true,
    promptTemplate: "请根据{知识点}生成{数量}道{难度}的高三数学题，包含解析与易错点提示。",
  },
  {
    id: "sk-002",
    name: "作文智能批改助手",
    description: "上传学生作文图片或文本，按高考作文评分标准给出分项评分、批注与升格建议。",
    icon: "✍️",
    subject: "语文",
    type: "批改",
    scope: "public",
    status: "published",
    ownerName: "学校教务处",
    usageCount: 986,
    rating: 4.7,
    official: true,
    promptTemplate: "请按高考作文评分标准批改以下作文，给出总分、分项得分与修改建议：{作文内容}",
  },
  {
    id: "sk-003",
    name: "期中试卷智能审题",
    description: "自动核查试卷知识点覆盖率、难度梯度、重复题型，并给出命题偏差预警。",
    icon: "🔍",
    subject: "通用",
    type: "审题",
    scope: "public",
    status: "published",
    ownerName: "学校教务处",
    usageCount: 512,
    rating: 4.6,
    official: true,
    promptTemplate: "请审核以下试卷的知识点覆盖、难度分布与题型重复情况：{试卷内容}",
  },
  {
    id: "sk-004",
    name: "英语听说课教案生成器",
    description: "输入教材单元与课时目标，生成含情境导入、活动设计、板书设计的完整教案。",
    icon: "📘",
    subject: "英语",
    type: "教案",
    scope: "public",
    status: "published",
    ownerName: "学校教务处",
    usageCount: 734,
    rating: 4.5,
    official: true,
    promptTemplate: "请为{教材单元}生成一份45分钟英语听说课教案，目标是{课时目标}。",
  },
  {
    id: "sk-005",
    name: "物理压轴题变式训练",
    description: "张明老师沉淀的个人 Skill：基于一道压轴题自动生成 5 道变式题，用于培优训练。",
    icon: "🧲",
    subject: "数学",
    type: "命题",
    scope: "private",
    status: "published",
    ownerName: "张明",
    usageCount: 58,
    rating: 4.9,
    official: false,
    promptTemplate: "基于以下压轴题生成 5 道难度相近的变式题：{原题}",
  },
  {
    id: "sk-006",
    name: "文言文情境化默写生成",
    description: "李芳老师创建：结合课文情境自动生成理解性默写题，覆盖高考64篇必背篇目。",
    icon: "📜",
    subject: "语文",
    type: "命题",
    scope: "private",
    status: "pending",
    ownerName: "李芳",
    usageCount: 21,
    rating: 4.8,
    official: false,
    promptTemplate: "请为《{篇目}》生成 8 道理解性默写题。",
  },
  {
    id: "sk-007",
    name: "数学错题本智能归因",
    description: "张明老师创建的草稿：分析班级错题数据，自动归因知识薄弱点并生成专项讲义。",
    icon: "📊",
    subject: "数学",
    type: "其他",
    scope: "private",
    status: "draft",
    ownerName: "张明",
    usageCount: 3,
    rating: 0,
    official: false,
    promptTemplate: "请分析以下错题数据并归因知识薄弱点：{错题数据}",
  },
];

export const knowledgeDocs: KnowledgeDoc[] = [
  { id: "kb-001", name: "2026版高中数学课程标准.pdf", subject: "数学", type: "课程标准", chunks: 340, updatedAt: "2026-08-20", visibility: "全校可见" },
  { id: "kb-002", name: "近五年高考数学真题汇编.pdf", subject: "数学", type: "历年真题", chunks: 812, updatedAt: "2026-09-01", visibility: "全校可见" },
  { id: "kb-003", name: "统编版语文必修上册教材.pdf", subject: "语文", type: "教材", chunks: 456, updatedAt: "2026-07-15", visibility: "语文组可见" },
  { id: "kb-004", name: "高三年级英语校本资料.docx", subject: "英语", type: "校本资料", chunks: 198, updatedAt: "2026-09-05", visibility: "高三年级组可见" },
  { id: "kb-005", name: "物理实验操作规范手册.pdf", subject: "物理", type: "校本资料", chunks: 76, updatedAt: "2026-06-30", visibility: "物理组可见" },
];

export const creditLedger: CreditTransaction[] = [
  { id: "cr-001", userName: "张明", change: -12, reason: "AI助手对话（DeepSeek-V3）", createdAt: "2026-09-15 09:20" },
  { id: "cr-002", userName: "李芳", change: -35, reason: "AI创作中心 · PPT生成", createdAt: "2026-09-15 08:55" },
  { id: "cr-003", userName: "陈静", change: -8, reason: "Skill调用 · 作文智能批改助手", createdAt: "2026-09-14 20:10" },
  { id: "cr-004", userName: "系统", change: 500, reason: "管理员充值 · 学科组月度额度发放", createdAt: "2026-09-01 00:00" },
  { id: "cr-005", userName: "刘洋", change: -60, reason: "AI创作中心 · 数字人视频生成", createdAt: "2026-08-28 15:44" },
];

export const modelConfigs: ModelConfig[] = [
  { id: "m-001", name: "DeepSeek-V3", provider: "DeepSeek", creditMultiplier: 1.0, status: "enabled", successRate: 99.2, latencyMs: 820 },
  { id: "m-002", name: "通义千问-Max", provider: "阿里云", creditMultiplier: 1.2, status: "enabled", successRate: 98.7, latencyMs: 960 },
  { id: "m-003", name: "文心一言 4.0", provider: "百度", creditMultiplier: 1.1, status: "enabled", successRate: 97.9, latencyMs: 1100 },
  { id: "m-004", name: "GPT-4o", provider: "OpenAI（代理接入）", creditMultiplier: 2.5, status: "disabled", successRate: 99.5, latencyMs: 1400 },
];

function msg(role: ChatMessage["role"], content: string, offsetMin: number, extra: Partial<ChatMessage> = {}): ChatMessage {
  return {
    id: crypto.randomUUID(),
    role,
    content,
    createdAt: Date.now() - offsetMin * 60_000,
    tokens: Math.round(content.length * 1.6),
    ...extra,
  };
}

export const initialConversations: Conversation[] = [
  {
    id: "conv-001",
    title: "高二数学《函数单调性》命题",
    updatedAt: Date.now() - 20 * 60_000,
    pinned: true,
    messages: [
      msg("user", "帮我出5道高二数学函数单调性的选择题，中等难度，要有详细解析。", 25),
      msg(
        "assistant",
        "好的，已调用【高考数学命题助手】Skill，并检索了《2026版高中数学课程标准》与近五年真题库中函数单调性相关题目，正在为你生成 5 道中等难度选择题（含解析）…",
        24,
        { invokedSkillId: "sk-001", citedDocIds: ["kb-001", "kb-002"] },
      ),
    ],
  },
  {
    id: "conv-002",
    title: "作文《这个瞬间，让我心动》批改",
    updatedAt: Date.now() - 3 * 60 * 60_000,
    messages: [
      msg("user", "帮我批改一篇学生作文，题目是《这个瞬间，让我心动》。", 190),
      msg("assistant", "已调用【作文智能批改助手】，从立意、结构、语言、书写四个维度进行评分…", 189, { invokedSkillId: "sk-002" }),
    ],
  },
  {
    id: "conv-003",
    title: "期中英语听说课教案",
    updatedAt: Date.now() - 26 * 60 * 60_000,
    messages: [
      msg("user", "帮我做一份 Unit 3 Travel 的听说课教案，45分钟。", 1600),
      msg("assistant", "已调用【英语听说课教案生成器】，教案包含情境导入、听力活动、口语输出与板书设计…", 1599, { invokedSkillId: "sk-004" }),
    ],
  },
];
